### ISSUE TITLE
Use more specific type for arrays of objects

### ISSUE THREAD

**Issue by leo60228** [JuliaIO/JSON.jl#278] opened 2019-01-27 22:37 UTC
Currently, `typeof(JSON.parse("""{"arr": [{"a": "b"}, {"c": "d"}]}""")["arr"])` is `Any[]`, despite `typeof(JSON.parse("""{"arr": [{"a": "b"}, {"c": "d"}]}""")["arr"][1])` and `typeof(JSON.parse("""{"arr": [{"a": "b"}, {"c": "d"}]}""")["arr"][2])` both being `Dict{String, Any}`.

**Comment by TotalVerb** [comment] 2020-01-11 03:38
duplicate of #139

**Closed** 2020-01-11 03:38 UTC
Labels: duplicate
