### ISSUE TITLE
JSON.parse from readme example no longer exists. 

### ISSUE THREAD

**Issue by wolfiex** [JuliaIO/JSON.jl#191] opened 2017-04-06 01:45 UTC
Fresh install and upgrade of JSON package.

**Comment by TotalVerb** [comment] 2017-04-06 04:06
Which one no longer exists? Can you post a minimal reproduction?

**Comment by TotalVerb** [comment] 2017-04-11 21:21
Since the function certainly still exists, I'm closing this issue. If you can find an example reproducing the problem, please open a new one.

**Closed by TotalVerb** 2017-04-11 21:21 UTC
