### ISSUE TITLE
Cannot serialize type DataArrays.NAtype

### ISSUE THREAD

**Issue by disleyland** [JuliaIO/JSON.jl#203] opened 2017-05-07 22:45 UTC
JSON.json is failing when there are NAs in a string data array

**Comment by TotalVerb** [comment] 2017-05-08 04:43
What is the expected behavior? `null`?

**Comment by quinnj** [comment] 2017-05-08 05:12
That's what I would expect.

**Comment by TotalVerb** [comment] 2017-05-08 05:14
This can't be fixed in JSON.jl because we can't define anything on `DataArrays.NAtype` without requiring it, and JSON is the more fundamental package here. Please raise an issue on `DataArrays`.

**Closed by TotalVerb** 2017-05-08 05:14 UTC

**Comment by nalimilan** [comment] 2017-05-08 10:46
What kind of methods should be defined in DataArrays to fix this? Cannot JSON.jl simply call `string`, which would return `"NA"`?

**Comment by TotalVerb** [comment] 2017-05-08 15:41
To be consistent with `Nullable`, we shouldn't use `"NA"` but rather `null` as the JSON equivalent. JSON does not try to guess at which objects want to be serialized as strings. We could serialize all singleton objects as strings, but that behavior seems unintuitive to me. Alternatively, we could serialize all singleton objects as `null`, but that also sounds suspicious. The best solution (as is being done right now) is probably to simply fail and leave it up to the package author.

The method that would need to be defined is

```
JSON.lower(::NAtype) = nothing
```

**Comment by TotalVerb** [comment] 2017-05-08 15:48
I'm not opposed to a blanket rule saying "serialize all singleton objects as _______" either: but we would need to bikeshed whether this should be `string`, `null`, or something else.

**Comment by nalimilan** [comment] 2017-05-08 15:50
I really don't know, and the goal is to move to a common representation for missingness quite soon anyway. But clearly we don't want DataArrays to depend on JSON, and for now we don't have optional modules.

**Comment by TotalVerb** [comment] 2017-05-08 15:57
I wonder if it would make sense to move JSON.lower to a minimal `IOBase` package that just serves as a namespace to contain `lower` and related functions. Then we can avoid a JSON dependency; an IOBase one probably isn't so bad?

**Comment by disleyland** [comment] 2017-05-08 15:59
speaking from the perspective that when I use JSON.jl, the file is to be processed by scripts in a browser, the old julia position was odd because it treated missingness as {} in the output string, which then got interpreted as an blank object in a browser based javascripting environment.  in the browser, to then check if this object was truly empty or hiding some other useful information, we'd need to have further checks which is a coding annoyance when trying to build re-usable code for lots of JSON outputs from Julia.  Seems very sensible for JSON.jl to treat NA as nothing (is that different then null?) as the resulting string is unambiguous when processed in a browser

**Comment by nalimilan** [comment] 2017-05-08 16:08
> I wonder if it would make sense to move JSON.lower to a minimal IOBase package that just serves as a namespace to contain lower and related functions. Then we can avoid a JSON dependency; an IOBase one probably isn't so bad?

But `lower` wouldn't have any meaning apart from "the JSON representation for an object", right? For example, when writing a CSV file, we want a different representation, etc.

**Comment by TotalVerb** [comment] 2017-05-08 20:53
It actually went from the empty object to an error in the 0.9.0 series, I believe.

**Comment by TotalVerb** [comment] 2017-05-08 20:53
It actually went from the empty object to an error in the 0.9.0 series, I believe.

**Comment by nalimilan** [comment] 2017-05-09 07:22
Yes, but that still wouldn't be a completely generic IOBase package. Anyway I would say we'd better wait for the new nullable framework in the next Julia version.

**Comment by TotalVerb** [comment] 2017-05-10 03:58
`Nullable` is already supported by JSON, since it's in base. However `NAtype` is difficult to support without blanket-changing the behavior of all singleton types, which is questionable.
